### ISSUE TITLE
Missing version

### ISSUE THREAD

**Issue by choonho** [Gaurav122000/private-registry#1]
In a Deployment file, docker image version is also required.

~~~
    spec:
      containers:
      - name: nginx
        image: gaurav122000/myplugin:0.1  
~~~

**Comment by Gaurav122000** [comment]
Please check the update

**Comment by Gaurav122000** [comment]
@choonho I didn't understand what you mean by my docker image version please can you give me an example

**Comment by choonho** [comment]
My comment was
Adding Docker tag

You fixed correctly.

![image](https://github.com/Gaurav122000/private-registry/assets/3993088/42104adf-2baa-4d1f-9583-89d02d886db6)
